/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "HistoryPyramid": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "PyramidDB": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}